name: Run Tests

on:
  push:
    branches: ["*"]

jobs:
  test:
    name: CDK Tests
    runs-on: ubuntu-latest
    container:
      image: "node:16"
    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v2
      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install NPM Packages
        run: npm ci

      - name: ğŸƒğŸ» Run NPM Tests
        run: npm run test
