name: Build and Publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:

  metadata:
    name: Gather Metadata
    runs-on: ubuntu-20.04
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  test:
    name: CDK Tests
    runs-on: ubuntu-20.04
    container:
      image: "node:16"
    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v2
      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install NPM Packages
        run: npm ci

      - name: ğŸƒğŸ» Run NPM Tests
        run: npm run test

  publish_github:
    name: "Publish Github NPM Module"
    needs: [metadata, test]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.metadata.outputs.branch_name }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@zerocube'

      - run: |
          npm ci
          npm run build

      # Push to GitHub Packages
      - if: ${{ needs.metadata.outputs.branch_name != 'main' }}
        run: npm publish --access public --tag ${{ needs.metadata.outputs.branch_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ needs.metadata.outputs.branch_name == 'main' }}
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_npm:
    name: "Publish Public NPM Module"
    needs: [metadata, test, version]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.metadata.outputs.branch_name }}

      # Push to NPM registry
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          scope: '@zerocube'

      - run: |
          npm ci
          npm run build

      # Push to GitHub Packages
      - if: ${{ needs.metadata.outputs.branch_name != 'main' }}
        run: npm publish --access public --tag ${{ needs.metadata.outputs.branch_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - if: ${{ needs.metadata.outputs.branch_name == 'main' }}
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
