name: Build and Publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:

  metadata:
    name: Gather Metadata
    runs-on: ubuntu-20.04
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  test:
    name: CDK Tests
    runs-on: ubuntu-20.04
    container:
      image: "node:16"
    steps:
      - name: üíæ Checkout code
        uses: actions/checkout@v2
      - name: üîß Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install NPM Packages
        run: npm ci

      - name: üèÉüèª Run NPM Tests
        run: npm run test

  version:
    name: Bump Version
    needs: [metadata, test]
    runs-on: ubuntu-20.04
    concurrency: versioning
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'

      - if: ${{ needs.metadata.outputs.branch_name == 'main' }}
        name: Create NPM patch version
        run: npm version patch
      - if: ${{ needs.metadata.outputs.branch_name != 'main' }}
        name: Create NPM patch version
        run: npm version prepatch --preid "${{ needs.metadata.outputs.branch_name }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  publish_github:
    name: "Publish Github NPM Module"
    needs: [metadata, test, version]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.metadata.outputs.branch_name }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@zerocube'

      - run: |
          npm ci
          npm run build

      # Push to GitHub Packages
      - if: ${{ needs.metadata.outputs.branch_name != 'main' }}
        run: npm publish --access public --tag ${{ needs.metadata.outputs.branch_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ needs.metadata.outputs.branch_name == 'main' }}
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_npm:
    name: "Publish Public NPM Module"
    needs: [metadata, test, version]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.metadata.outputs.branch_name }}

      # Push to NPM registry
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          scope: '@zerocube'

      - run: |
          npm ci
          npm run build

      # Push to GitHub Packages
      - if: ${{ needs.metadata.outputs.branch_name != 'main' }}
        run: npm publish --access public --tag ${{ needs.metadata.outputs.branch_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - if: ${{ needs.metadata.outputs.branch_name == 'main' }}
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
